services:

    trinity.search:
        class: Trinity\SearchBundle\Search
        arguments: ["@trinity.search.dql_converter"]

    trinity.search.dql_converter:
        class: Trinity\SearchBundle\NQL\DQLConverter
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
