services:

    trinity.search.detail_url_provider:
        class: Trinity\Bundle\SearchBundle\DetailUrlProvider
        arguments: ["@router"]

    trinity.search:
        class: Trinity\Bundle\SearchBundle\Search
        arguments: ["@doctrine.orm.entity_manager", "@trinity.search.dql_converter", "%trinity.search.namespace%", "@service_container", "%trinity.search.detail_url_provider%"]

    trinity.search.dql_converter:
        class: Trinity\Bundle\SearchBundle\NQL\DQLConverter
        arguments: ["@doctrine.orm.entity_manager", "%trinity.search.doctrine_prefix%", "%trinity.search.namespace%"]